import { useEffect, useMemo, useState } from "react";
import type { DemoUser } from "../App";
import { getPorts } from "../services/portService";
import { downloadReport, getReportPreview, type ReportFilters, type ReportPreview, type ReportType } from "../services/reportService";
import type { PortSummary } from "../types/port";
import { riskLabel } from "../utils/displayLabels";

const titles: Record<ReportType, string> = { ALERTS: "Cảnh báo", TASKS: "Nhiệm vụ", EVENTS: "Nhật ký vận hành" };
function dateValue(offset: number) { const d = new Date(); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10); }

export function ReportPage({ currentUser }: { currentUser: DemoUser }) {
  const [ports, setPorts] = useState<PortSummary[]>([]); const [type, setType] = useState<ReportType>("ALERTS"); const [portCode, setPortCode] = useState("ALL"); const [zoneName, setZoneName] = useState("ALL"); const [riskLevel, setRiskLevel] = useState("ALL"); const [from, setFrom] = useState(dateValue(-7)); const [to, setTo] = useState(dateValue(0)); const [preview, setPreview] = useState<ReportPreview | null>(null); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void getPorts().then(items => { const allowed = currentUser.role === "PORT_MANAGER" && currentUser.portId ? items.filter(item => item.portId === currentUser.portId) : items; setPorts(allowed); if (currentUser.role === "PORT_MANAGER" && allowed[0]) setPortCode(allowed[0].portCode); }).catch(() => setPorts([])); }, [currentUser.portId, currentUser.role]);
  const filters = useMemo<ReportFilters>(() => ({ type, portCode, zoneName, riskLevel, from: `${from}T00:00:00Z`, to: `${to}T23:59:59Z` }), [type, portCode, zoneName, riskLevel, from, to]);
  async function loadPreview() { setLoading(true); setError(""); setMessage(""); try { setPreview(await getReportPreview(filters)); } catch (e) { setError(e instanceof Error ? e.message : "Không tải được dữ liệu báo cáo."); } finally { setLoading(false); } }
  async function exportFile(format: "xlsx" | "pdf") { setLoading(true); setError(""); try { await downloadReport(filters, format); setMessage(`Đã tạo báo cáo ${format.toUpperCase()} và ghi vào nhật ký vận hành.`); } catch (e) { setError(e instanceof Error ? e.message : "Không thể tạo báo cáo."); } finally { setLoading(false); } }
  return <section className="page-grid report-page">
    <div className="section-heading report-heading"><div><span className="eyebrow">TỔNG HỢP DỮ LIỆU</span><h1>Báo cáo vận hành</h1><p>Chọn phạm vi dữ liệu, xem trước kết quả rồi tải báo cáo phục vụ theo dõi và họp vận hành.</p></div><span className="report-scope">{currentUser.role === "ADMIN" ? "Toàn hệ thống cảng" : currentUser.portName}</span></div>
    <article className="card card-pad report-filter-card"><div className="card-head"><div><h3>Chọn nội dung báo cáo</h3><p>Port Manager chỉ được xuất dữ liệu của cảng mình phụ trách.</p></div></div><div className="report-type-tabs">{(Object.keys(titles) as ReportType[]).map(item => <button className={item === type ? "is-active" : ""} onClick={() => { setType(item); setPreview(null); }} type="button" key={item}>{titles[item]}</button>)}</div><div className="report-filter-grid"><label><span>Cảng</span><select className="input" value={portCode} onChange={e => setPortCode(e.target.value)}>{currentUser.role === "ADMIN" ? <option value="ALL">Tất cả cảng</option> : null}{ports.map(port => <option key={port.portId} value={port.portCode}>{port.portCode} - {port.portName}</option>)}</select></label><label><span>Khu vực</span><input className="input" value={zoneName === "ALL" ? "" : zoneName} onChange={e => setZoneName(e.target.value || "ALL")} placeholder="Tất cả khu vực" /></label><label><span>Mức độ</span><select className="input" value={riskLevel} onChange={e => setRiskLevel(e.target.value)} disabled={type === "EVENTS"}><option value="ALL">Tất cả mức độ</option><option value="LOW">Thấp</option><option value="MEDIUM">Cần lưu ý</option><option value="HIGH">Cao</option><option value="CRITICAL">Rất cao</option></select></label><label><span>Từ ngày</span><input className="input" type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label><span>Đến ngày</span><input className="input" type="date" value={to} onChange={e => setTo(e.target.value)} /></label><button className="button button-primary report-preview-button" disabled={loading} onClick={() => void loadPreview()} type="button">{loading ? "Đang tải..." : "Xem trước báo cáo"}</button></div></article>
    {message ? <p className="form-success">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}
    <article className="card card-pad report-preview-card"><div className="card-head"><div><span className="eyebrow">BẢN XEM TRƯỚC</span><h3>{preview ? `${titles[type]} · ${preview.totalRows} bản ghi` : "Chưa có dữ liệu xem trước"}</h3><p>{preview ? "Kiểm tra phạm vi và nội dung trước khi tải file." : "Chọn bộ lọc rồi bấm Xem trước báo cáo."}</p></div><div className="report-actions"><button className="button button-secondary" disabled={!preview?.totalRows || loading} onClick={() => void exportFile("xlsx")} type="button">Xuất Excel</button><button className="button button-primary" disabled={!preview?.totalRows || loading} onClick={() => void exportFile("pdf")} type="button">Xuất PDF</button></div></div>{preview?.totalRows ? <div className="report-table-shell"><table><thead><tr><th>Thời gian</th><th>Cảng & khu vực</th><th>Mức độ</th><th>Nội dung</th><th>Phụ trách/nguồn</th><th>Trạng thái</th></tr></thead><tbody>{preview.rows.map((row, index) => <tr key={`${row.occurredAt}-${index}`}><td>{new Date(row.occurredAt).toLocaleString("vi-VN")}</td><td><strong>{row.portCode} · {row.portName}</strong><small>{row.zoneName}</small></td><td>{row.riskLevel ? <span className={`badge badge-${row.riskLevel === "CRITICAL" ? "danger" : row.riskLevel === "HIGH" ? "warning" : "info"}`}>{riskLabel(row.riskLevel)}</span> : "-"}</td><td><strong>{row.subject}</strong><small>{row.description}</small></td><td>{row.owner}</td><td>{row.status}</td></tr>)}</tbody></table></div> : preview ? <div className="report-empty">Không tìm thấy dữ liệu phù hợp với bộ lọc hiện tại.</div> : null}</article>
  </section>;
}
